import { Diamond } from "@/lib/filter-types";

export const mockDiamonds: Diamond[] = [
  {
    id: "147841971",
    lab: "Natural",
    carat: 1.0,
    color: "K",
    clarity: "SI2",
    cut: "Very Good",
    shape: "Round",
    price: 805,
    compValue: 1160,
    quality: "13/18",
    certification: "GIA",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "139342592",
    lab: "Natural",
    carat: 1.01,
    color: "G",
    clarity: "SI2",
    cut: "Very Good",
    shape: "Round",
    price: 1455,
    compValue: 2105,
    quality: "14/18",
    certification: "GIA",
    quickShip: false,
    deliveryByHoliday: true,
  },
  {
    id: "168394205",
    lab: "Natural",
    carat: 1.04,
    color: "F",
    clarity: "SI2",
    cut: "Rare Carat Ideal",
    shape: "Round",
    price: 1840,
    compValue: 2670,
    quality: "16/18",
    certification: "GIA",
    quickShip: true,
    deliveryByHoliday: false,
  },
  {
    id: "156982447",
    lab: "Natural",
    carat: 1.12,
    color: "H",
    clarity: "VS2",
    cut: "Excellent",
    shape: "Oval",
    price: 2385,
    compValue: 3410,
    quality: "15/18",
    certification: "IGI",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "132771904",
    lab: "Natural",
    carat: 1.18,
    color: "I",
    clarity: "VS1",
    cut: "Excellent",
    shape: "Cushion",
    price: 2510,
    compValue: 3595,
    quality: "15/18",
    certification: "GIA",
    quickShip: false,
    deliveryByHoliday: true,
  },
  {
    id: "170284639",
    lab: "Natural",
    carat: 1.21,
    color: "D",
    clarity: "SI1",
    cut: "Good",
    shape: "Emerald",
    price: 2675,
    compValue: 3890,
    quality: "14/18",
    certification: "GCAL",
    quickShip: true,
    deliveryByHoliday: false,
  },
  {
    id: "128849351",
    lab: "Natural",
    carat: 1.28,
    color: "E",
    clarity: "VS2",
    cut: "Rare Carat Ideal",
    shape: "Princess",
    price: 2960,
    compValue: 4210,
    quality: "17/18",
    certification: "GIA",
    quickShip: false,
    deliveryByHoliday: true,
  },
  {
    id: "144820652",
    lab: "Natural",
    carat: 1.36,
    color: "G",
    clarity: "VVS2",
    cut: "Excellent",
    shape: "Radiant",
    price: 3345,
    compValue: 4780,
    quality: "16/18",
    certification: "IGI",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "151009837",
    lab: "Natural",
    carat: 1.42,
    color: "H",
    clarity: "SI1",
    cut: "Very Good",
    shape: "Pear",
    price: 3510,
    compValue: 5015,
    quality: "14/18",
    certification: "GIA",
    quickShip: false,
    deliveryByHoliday: false,
  },
  {
    id: "160550284",
    lab: "Natural",
    carat: 1.51,
    color: "F",
    clarity: "VS1",
    cut: "Rare Carat Ideal",
    shape: "Round",
    price: 3895,
    compValue: 5565,
    quality: "17/18",
    certification: "GIA",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "149233704",
    lab: "Natural",
    carat: 1.62,
    color: "J",
    clarity: "VVS1",
    cut: "Excellent",
    shape: "Marquise",
    price: 4130,
    compValue: 5890,
    quality: "15/18",
    certification: "IGI",
    quickShip: false,
    deliveryByHoliday: true,
  },
  {
    id: "171450992",
    lab: "Natural",
    carat: 1.74,
    color: "E",
    clarity: "IF",
    cut: "Rare Carat Ideal",
    shape: "Asscher",
    price: 4585,
    compValue: 6540,
    quality: "18/18",
    certification: "GIA",
    quickShip: true,
    deliveryByHoliday: false,
  },
  {
    id: "121784550",
    lab: "Natural",
    carat: 1.83,
    color: "I",
    clarity: "VS2",
    cut: "Excellent",
    shape: "Heart",
    price: 4890,
    compValue: 6975,
    quality: "15/18",
    certification: "GCAL",
    quickShip: false,
    deliveryByHoliday: true,
  },
  {
    id: "163788214",
    lab: "Natural",
    carat: 2.01,
    color: "G",
    clarity: "SI1",
    cut: "Very Good",
    shape: "Round",
    price: 5260,
    compValue: 7510,
    quality: "14/18",
    certification: "GIA",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "154902681",
    lab: "Natural",
    carat: 2.12,
    color: "D",
    clarity: "VVS2",
    cut: "Excellent",
    shape: "Oval",
    price: 5845,
    compValue: 8335,
    quality: "17/18",
    certification: "GIA",
    quickShip: false,
    deliveryByHoliday: false,
  },
  {
    id: "166029755",
    lab: "Natural",
    carat: 2.27,
    color: "F",
    clarity: "FL",
    cut: "Rare Carat Ideal",
    shape: "Cushion",
    price: 6420,
    compValue: 9150,
    quality: "18/18",
    certification: "GIA",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "138540126",
    lab: "Natural",
    carat: 2.43,
    color: "H",
    clarity: "VVS1",
    cut: "Excellent",
    shape: "Emerald",
    price: 6895,
    compValue: 9845,
    quality: "16/18",
    certification: "IGI",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "177311608",
    lab: "Natural",
    carat: 2.71,
    color: "E",
    clarity: "VS1",
    cut: "Rare Carat Ideal",
    shape: "Round",
    price: 7840,
    compValue: 11200,
    quality: "18/18",
    certification: "GIA",
    quickShip: false,
    deliveryByHoliday: false,
  },
  {
    id: "182440916",
    lab: "Lab",
    carat: 1.05,
    color: "D",
    clarity: "VVS1",
    cut: "Rare Carat Ideal",
    shape: "Round",
    price: 910,
    compValue: 1300,
    quality: "17/18",
    certification: "IGI",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "188213405",
    lab: "Lab",
    carat: 1.56,
    color: "E",
    clarity: "VS1",
    cut: "Excellent",
    shape: "Oval",
    price: 1325,
    compValue: 1890,
    quality: "16/18",
    certification: "IGI",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "180945672",
    lab: "Lab",
    carat: 2.03,
    color: "F",
    clarity: "VS2",
    cut: "Rare Carat Ideal",
    shape: "Radiant",
    price: 2175,
    compValue: 3105,
    quality: "17/18",
    certification: "GCAL",
    quickShip: false,
    deliveryByHoliday: false,
  },
  {
    id: "184739201",
    lab: "Lab",
    carat: 2.58,
    color: "G",
    clarity: "SI1",
    cut: "Excellent",
    shape: "Princess",
    price: 2860,
    compValue: 4085,
    quality: "15/18",
    certification: "IGI",
    quickShip: true,
    deliveryByHoliday: true,
  },
  {
    id: "189430778",
    lab: "Lab",
    carat: 3.02,
    color: "H",
    clarity: "VS2",
    cut: "Very Good",
    shape: "Pear",
    price: 3515,
    compValue: 5020,
    quality: "14/18",
    certification: "GCAL",
    quickShip: false,
    deliveryByHoliday: true,
  },
  {
    id: "181255693",
    lab: "Lab",
    carat: 4.01,
    color: "I",
    clarity: "VVS2",
    cut: "Excellent",
    shape: "Emerald",
    price: 5795,
    compValue: 8275,
    quality: "16/18",
    certification: "IGI",
    quickShip: true,
    deliveryByHoliday: false,
  },
];

export function formatDiamondTitle(diamond: Diamond) {
  return `${diamond.carat.toFixed(2)}ct ${diamond.color} ${diamond.clarity} ${diamond.cut} Cut ${diamond.shape} Diamond`;
}
